### ISSUE TITLE
ViewPager scrolls back immediately to the first item when there are only two items

### ISSUE THREAD

**Issue by Sonphil** [therealshabi/AutoImageFlipper#38] opened 2020-02-23 06:13 UTC
When the user scrolls to the second item, if the layout has only two `FlipperView`s, the `ViewPager` scrolls back immediately to the first item. The  `ViewPager` should remain at that position (or switch after a certain amount of time if auto cycle is enabled).

Here is an example:
![ezgif-6-444070d61c5f](https://user-images.githubusercontent.com/22182973/75104573-fb8f7080-55d8-11ea-8d9d-e2e0bd0ed184.gif)

This problem doesn't occur when there are more than two `FlipperView`s.
![ezgif-6-153ac05e0290](https://user-images.githubusercontent.com/22182973/75104580-22e63d80-55d9-11ea-8ae1-f90fe701048a.gif)

Version of the library used: 1.6.0

**Comment by therealshabi** [comment] 2020-02-23 18:05
Hi @Sonphil 
Thanks for reporting this issue, will surely look into this. Meanwhile, if you want to fix this, you can contribute to it as well.

**Comment by Sonphil** [comment] 2020-02-23 18:30
@therealshabi I made a small change and opened a pull request: #39

**Comment by therealshabi** [comment] 2020-02-23 19:27
Merged your PR into the `dev` branch. Will merge and release from the master after testing the implementation. Thanks for your contribution

**Comment by Poornima-Dixit** [comment] 2020-03-15 11:36
How to set Multiple images in viewpager??

**Comment by Poornima-Dixit** [comment] 2020-03-15 11:45
view.setImage(url[i], new Function2<ImageView, Object, Unit>() {
                    @Override
                    public Unit invoke(ImageView imageView, Object image) {
                        Picasso.get().load((String) image).into(imageView);
                        return Unit.INSTANCE;
                    }
                });
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }

**Comment by Poornima-Dixit** [comment] 2020-03-15 11:45
The above code not working

**Comment by therealshabi** [comment] 2020-03-15 11:50
@Poornima-Dixit is it showing any error? What exactly is happening? Can you please share the stack trace?

**Comment by Poornima-Dixit** [comment] 2020-03-15 11:55
view.setImage(url[i], new Function2<ImageView, Object, Unit>() {
@override
public Unit invoke(ImageView imageView, Object image) {
Picasso.get().load((String) image).into(imageView);
return Unit.INSTANCE;
}
});
} catch (MalformedURLException e) {
e.printStackTrace();
}
The above code contains ERROR when I am running 
It's giving error on Function2 & Unit

**Comment by Poornima-Dixit** [comment] 2020-03-15 12:00
How to solve  can you plzzz help????

**Comment by Poornima-Dixit** [comment] 2020-03-15 12:01
@Sonphil

**Comment by Poornima-Dixit** [comment] 2020-03-15 12:01
@therealshabi

**Comment by therealshabi** [comment] 2020-03-15 12:37
@Poornima-Dixit Are you using Java 8 in your project, because this will work if your project is running on Java8?

**Comment by Poornima-Dixit** [comment] 2020-03-15 14:01
How to check that??Where it is mention in android studio?

**Comment by Poornima-Dixit** [comment] 2020-03-15 14:13
I am using Java 8 still giving error

**Comment by Poornima-Dixit** [comment] 2020-03-15 14:16
Have you used Kotlin??

**Comment by therealshabi** [comment] 2020-03-15 18:34
@Poornima-Dixit this library also has a Kotlin support, so you can use Kotlin syntax as well (for syntax please refer the [Readme](https://github.com/therealshabi/AutoImageFlipper/blob/master/README.md#methods-to-set-image-resource-into-the-flipper-view)).
 Having said that I'm curious why it is not working for you in Java. Can you please share the codebase or a test code for me if you can in which this code is not working. I'll try to debug and present the solution to you as soon as I can

**Comment by Poornima-Dixit** [comment] 2020-03-17 15:07
@therealshabi Yes sure 
The program is running when I am adding only one image
**MainActivity.java File:-**
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final FlipperLayout flipperLayout = findViewById(R.id.flipperLayoutTwo);

        String[] url = {"https://blog.eap.ucop.edu/wp-content/uploads/2016/01/Julie-Huang-27.jpg",
                "https://source.unsplash.com/random",
                "https://i.pinimg.com/originals/18/40/72/184072abb72399c23ab635faaa0a94ad.jpg"
        };
        for (int i = 0; i < url.length; i++) {
            FlipperView view = new FlipperView(getBaseContext());
            view.setDescription("Cool" + (i + 1))
                    .setDescriptionBackgroundColor(Color.TRANSPARENT)
                    .resetDescriptionTextView();
            flipperLayout.setCircleIndicatorHeight(60);
            flipperLayout.setCircleIndicatorWidth(200);
            flipperLayout.removeCircleIndicator();
            flipperLayout.showCircleIndicator();
            view.setOnFlipperClickListener(new FlipperView.OnFlipperClickListener() {
                @Override
                public void onFlipperClick(@NotNull FlipperView flipperView) {
                    Toast.makeText(getBaseContext(),
                            "Here " + (flipperLayout.getCurrentPagePosition() + 1), Toast.LENGTH_SHORT).show();
                }
            });

         view.setImageDrawable(R.drawable.lean);// this is only one image
      
          flipperLayout.addFlipperView(view);
        }

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        FloatingActionButton fab = findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
            }
        });
        DrawerLayout drawer = findViewById(R.id.drawer_layout);
        NavigationView navigationView = findViewById(R.id.nav_view);
        // Passing each menu ID as a set of Ids because each
        // menu should be considered as top level destinations.
        mAppBarConfiguration = new AppBarConfiguration.Builder(
                R.id.nav_home, R.id.nav_gallery, R.id.nav_slideshow)
                .setDrawerLayout(drawer)
                .build();
     //   NavController navController = Navigation.findNavController(this, R.id.nav_host_fragment);
       // NavigationUI.setupActionBarWithNavController(this, navController, mAppBarConfiguration);
  //      NavigationUI.setupWithNavController(navigationView, navController);
    }

**Comment by Poornima-Dixit** [comment] 2020-03-17 15:09
@therealshabi 
Now the Problem is that when I am adding below code its giving error:-
 try {
                view.setImage(url[i], new Function2<ImageView, Object, Unit>() {
                    @Override
                    public Unit invoke(ImageView imageView, Object image) {
                        Picasso.get().load((String) image).into(imageView);
                        return Unit.INSTANCE;
                    }
                });
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }

**Comment by Poornima-Dixit** [comment] 2020-03-20 10:39
@therealshabi

**Comment by therealshabi** [comment] 2020-03-20 11:03
@Poornima-Dixit I'll check this asap and will revert

**Comment by Poornima-Dixit** [comment] 2020-03-20 11:05
@therealshabi Yes sure please do it on ASAP.IT's urgent

**Comment by therealshabi** [comment] 2020-03-20 11:15
The images that you're trying to load, are they a drawable, url or what?

**Comment by Poornima-Dixit** [comment] 2020-03-20 11:31
Yes,they are drawable

**Comment by Poornima-Dixit** [comment] 2020-03-20 11:31
@therealshabi

**Comment by therealshabi** [comment] 2020-03-20 12:35
For drawable set image like: 
```Java
try {
    view.setImage(drawableList[i], new Function2<ImageView, Object, Unit>() {
        @Override
        public Unit invoke(ImageView imageView, Object image) {
            imageView.setImageDrawable((Drawable) image);
            return Unit.INSTANCE;
        }
    });
} catch (MalformedURLException e) {
    e.printStackTrace();
}
```

**Comment by Poornima-Dixit** [comment] 2020-03-20 13:29
@therealshabi Yes But it is giving error on"Function2" & "Unit"
Where is these classes available?

**Comment by therealshabi** [comment] 2020-03-20 13:36
Ohh! Are you having Kotlin dependency in your project, these are Java version of Kotlin callback method

**Comment by Poornima-Dixit** [comment] 2020-03-20 13:37
No I haven't added here ,How to add it??

**Comment by therealshabi** [comment] 2020-03-20 14:07
Can you please google it, it'll be a simple process.

**Comment by Poornima-Dixit** [comment] 2020-03-20 14:22
@therealshabi Yes I solved it.Just One Query I had

**Comment by Poornima-Dixit** [comment] 2020-03-20 14:23
@therealshabi May I Ask one query?

**Comment by Poornima-Dixit** [comment] 2020-03-20 14:34
@therealshabi Thank you so much for your support answers.Just last one error is "setImage"giving error.How to solve it

**Comment by therealshabi** [comment] 2020-03-20 14:51
Can you please specify clearly, what error it is giving?

**Comment by Poornima-Dixit** [comment] 2020-03-20 14:57
![error](https://user-images.githubusercontent.com/22894699/77175830-38238e80-6ae9-11ea-9239-fa6cc44a5229.png)

**Comment by Poornima-Dixit** [comment] 2020-03-20 15:13
@therealshabi above is the error

**Comment by therealshabi** [comment] 2020-03-20 17:24
This is weird, can you please clean and build the app and check again?

**Comment by Poornima-Dixit** [comment] 2020-03-20 17:34
Ok

**Closed** 2020-10-25 15:49 UTC
Labels: is:bug
